# Generated by Django 2.1.4 on 2018-12-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpageinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpageinstance',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpageinstance',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogger',
            name='bloggerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogpage'),
        ),
        migrations.DeleteModel(
            name='BlogpageInstance',
        ),
    ]
