# Generated by Django 2.1.4 on 2018-12-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181219_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter the description of this blog.', max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Blogpage')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='bloggerid',
        ),
    ]
