# Generated by Django 2.1.4 on 2018-12-27 02:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181224_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 27, 2, 24, 42, 406116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(help_text='Enter your comment for this blog.', max_length=1000),
        ),
    ]
