# Generated by Django 2.1.4 on 2018-12-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181226_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
